name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'ci'
      - 'build'
      - 'docs'
template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
autolabeler:
  - label: 'docs'
    files:
      - '*.md'
    branch:
      - '/docs{,/**}/'
  - label: 'build'
    files:
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradle/**'
    branch:
      - '/build{,/**}/'
  - label: 'ci'
    files:
      - '.github/workflows/*'
    branch:
      - '/ci{,/**}/'
